ByDSync/Controllers/ReportGrandController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ByDSync.Schema;

namespace ByDSync.Controllers
{
    public class ReportGrandController : Controller
    {
        private ByDMirrorEntities db = new ByDMirrorEntities();

        // GET: ReportGrand
        public ActionResult Index()
        {
            ViewData["ClosingStep"] = db.enum_container.Where(x => x.enumTypeId == "CLSSTPGL").ToList();

            return View(db.ReportGLs.ToList());
        }

        // GET: ReportGrand/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ReportGL reportGL = db.ReportGLs.Find(id);
            if (reportGL == null)
            {
                return HttpNotFound();
            }
            return View(reportGL);
        }

        // GET: ReportGrand/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ReportGrand/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "C_uid,Posting_Date,Journal_ID,GL_Account,Amount,Dr_Cr,Profit_Center,Project_ID,Custom_Code_3,Funding_Source_1,GL_Account_Name,Account_Type,Department_No_,Department_Name,Project_Name,Supplier_Name,Document_Source_Type,Description")] ReportGL reportGL)
        {
            if (ModelState.IsValid)
            {
                db.ReportGLs.Add(reportGL);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(reportGL);
        }
        
        [HttpPost]
        public ActionResult Filter()
        {
            ViewBag.StepClosing = db.enum_container.Where(x => x.enumTypeId == "CLSSTPGL").ToList();

            DateTime fromDate = Request["begin"].ToString() != "" ? DateTime.Parse(Request["begin"].ToString()).Date : DateTime.MinValue.Date;
            DateTime todate = Request["end"].ToString() != "" ? DateTime.Parse(Request["end"].ToString()).Date : DateTime.MaxValue.Date;
            string closingStep = Request["closingStep"];

            ViewBag.closingStep = closingStep;
            ViewBag.fromDate = fromDate.ToString("yyyy-MM-dd");
            ViewBag.todate = todate.ToString("yyyy-MM-dd");

            var modelFilter = db.ReportGLs.Where(x => x.Posting_Date >= fromDate && x.Posting_Date <= todate && x.Closing_Step_Code == closingStep).ToList();

            return View(modelFilter);
        }

        // GET: ReportGrand/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ReportGL reportGL = db.ReportGLs.Find(id);
            if (reportGL == null)
            {
                return HttpNotFound();
            }
            return View(reportGL);
        }

        // POST: ReportGrand/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "C_uid,Posting_Date,Journal_ID,GL_Account,Amount,Dr_Cr,Profit_Center,Project_ID,Custom_Code_3,Funding_Source_1,GL_Account_Name,Account_Type,Department_No_,Department_Name,Project_Name,Supplier_Name,Document_Source_Type,Description")] ReportGL reportGL)
        {
            if (ModelState.IsValid)
            {
                db.Entry(reportGL).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(reportGL);
        }

        // GET: ReportGrand/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ReportGL reportGL = db.ReportGLs.Find(id);
            if (reportGL == null)
            {
                return HttpNotFound();
            }
            return View(reportGL);
        }

        // POST: ReportGrand/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            ReportGL reportGL = db.ReportGLs.Find(id);
            db.ReportGLs.Remove(reportGL);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ByDSync/Views/ReportGrand/Create.cshtml
@model ByDSync.Schema.ReportGL

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ReportGL</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.C_uid, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.C_uid, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.C_uid, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Posting_Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Posting_Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Posting_Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Journal_ID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Journal_ID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Journal_ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GL_Account, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GL_Account, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GL_Account, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Dr_Cr, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Dr_Cr, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Dr_Cr, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Profit_Center, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Profit_Center, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Profit_Center, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Project_ID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Project_ID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Project_ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Custom_Code_3, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Custom_Code_3, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Custom_Code_3, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Funding_Source_1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Funding_Source_1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Funding_Source_1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GL_Account_Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GL_Account_Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GL_Account_Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Account_Type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Account_Type, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Account_Type, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Department_No_, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Department_No_, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Department_No_, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Department_Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Department_Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Department_Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Project_Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Project_Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Project_Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Supplier_Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Supplier_Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Supplier_Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Document_Source_Type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Document_Source_Type, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Document_Source_Type, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ByDSync/Views/ReportGrand/Filter.cshtml
@using ByDSync.Schema
@model IEnumerable<ByDSync.Schema.ReportGL>

@{
    ViewBag.Title = "Index";
}

<style>
    th, td {
        border: 7px solid transparent;
    }

    * {
        box-sizing: border-box
    }

    .container {
        width: 100%;
    }

    /* Style the tab */
    .tab {
        float: left;
        border: 1px solid #ccc;
        background-color: #f1f1f1;
        width: 10%;
        height: 300px;
    }

        /* Style the buttons that are used to open the tab content */
        .tab button {
            display: block;
            background-color: inherit;
            color: black;
            padding: 22px 16px;
            width: 100%;
            border: none;
            outline: none;
            text-align: left;
            cursor: pointer;
            transition: 0.3s;
        }

            /* Change background color of buttons on hover */
            .tab button:hover {
                background-color: #ddd;
            }

            /* Create an active/current "tab button" class */
            .tab button.active {
                background-color: #ccc;
            }

    /* Style the tab content */
    .tabcontent {
        float: left;
        padding: 0px 12px;
        border: 1px solid #ccc;
        width: 90%;
        border-left: none;
    }

    #filter {
        padding: 15px;
        margin-inline: 150px;
    }

        #filter button {
            margin-inline-start: 10px;
        }
</style>

<div class="tab">
    <button class="tablinks" onclick="openReport(event, 'Grand')">Report Grand</button>
    <button class="tablinks" onclick="openReport(event, 'Total')">Report Total</button>
    <button class="tablinks" onclick="openReport(event, 'Coa')">Report Detail COA</button>
</div>

@{
    var stepClosing = ViewBag.StepClosing as IEnumerable<enum_container>;
}

<div id="filter">
    @using (Html.BeginForm("Filter", "ReportGrand", FormMethod.Post))
    {
        @Html.Label("From")
        <input type="date" name="begin" placeholder="@ViewBag.fromDate" value="@ViewBag.fromDate" min="1997-01-01" max="2050-12-31">
        @Html.Label("To")
        <input type="date" name="end" placeholder="@ViewBag.toDate" value="@ViewBag.toDate" min="1997-01-01" max="2050-12-31">
        @Html.Label("Closing Step")
        <select name="closingStep" id="cars">
            @foreach (var val in stepClosing)
            {
                <option value="@val.enumNumber">@val.enumDescription</option>
            }
        </select>
        <button type="submit" onclick="location.href = '@Url.Action("Filter", "ReportGrand")'">Filter Report</button>
    }
</div>

<div id="Grand" class="tabcontent">
    <h2>Report Grand</h2>
    @{
        var groupGrand = Model.GroupBy(x => x.Funding_Source_1, (key, g) => new { FundingSource = key, SumGrand = g.Sum(x => x.Amount) });
        //var detailGrand = Model.ToList();
    }

    <table>
        <thead>
            <tr>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
            </tr>
        </thead>

        <tbody>

            @foreach (var itemGrand in groupGrand)
            {
                string fundingGrand = itemGrand.FundingSource != null ? itemGrand.FundingSource : "N/A";

                <tr>
                    <td colspan="4"><h4>Grand :  @fundingGrand</h4></td>
                </tr>

                var detailGrand = (from r in Model
                                   where r.Funding_Source_1 == itemGrand.FundingSource
                                   group r by r.GL_Account into newDetail
                                   orderby newDetail.Key
                                   select newDetail);

                string sumGrand = itemGrand.SumGrand >= 0 ? "Rp. " + ((decimal)itemGrand.SumGrand).ToString("##,#") + ",00" : "Rp. " + ((decimal)itemGrand.SumGrand).ToString("##,#").Replace('-', '(') + ",00)";

                foreach (var detail in detailGrand)
                {
                    var sumAmount = detail.Sum(x => x.Amount);

                    string amountString = sumAmount >= 0 ? "Rp. " + ((decimal)sumAmount).ToString("##,#") + ",00" : "Rp. " + ((decimal)sumAmount).ToString("##,#").Replace('-', '(') + ",00)";

                    <tr>
                        <td></td>
                        <td><b>@detail.Key</b></td>
                        <td>@detail.First().GL_Account_Name.ToUpper()</td>
                        <td>@amountString</td>
                    </tr>
                }

                <tr>
                    <td colspan="4" align="right">@sumGrand</td>
                </tr>

            }
        </tbody>

    </table>
</div>

<div id="Total" class="tabcontent">
    <h2>Total</h2>

    @{
        var groupAccount = (from r in Model group r by r.GL_Account into account select account);

        decimal sumAll = (decimal)Model.Sum(x => x.Amount);
        string sumAllString = sumAll >= 0 ? "Rp. " + sumAll.ToString("#,##") + ",00" : "Rp. " + sumAll.ToString("#,##").Replace('-', '(') + ",00)";

        <table>

            @foreach (var akun in groupAccount)
            {
                decimal summa = (decimal)akun.Sum(x => x.Amount);
                var sumAccount = summa >= 0 ? "Rp. " + summa.ToString("#,##") + ",00" : "Rp. " + summa.ToString("#,##").Replace('-', '(') + ",00)";

                <tr>
                    <td><b>@akun.Key</b></td>
                    <td>@akun.First().GL_Account_Name.ToUpper() </td>
                    <td>@sumAccount</td>
                </tr>

            }

            <tr>
                <td colspan="3" align="right">
                    @sumAllString
                </td>
            </tr>

        </table>
    }
</div>

<div id="Coa" class="tabcontent">
    <h3>Detail COA</h3>

    <table>
        <thead>
            <tr>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @{
                var groupAcct = (from r in Model group r by r.GL_Account into newAccount select newAccount);

                foreach (var act in groupAcct)
                {
                    var groupFund = (from r in Model where r.GL_Account == act.Key group r by r.Funding_Source_1 into newFund select newFund);

                    <tr>
                        <td><h4>@act.Key</h4></td>
                        <td colspan="3"><h4>@act.First().GL_Account_Name.ToUpper()</h4></td>
                    </tr>

                    foreach (var fund in groupFund)
                    {
                        string keyAccount = fund.Key != null ? fund.Key : "N/A";

                        decimal amountDeb = (decimal)fund.Where(x => x.Dr_Cr == "DEBIT").Sum(x => x.Amount);
                        decimal amountKre = (decimal)fund.Where(x => x.Dr_Cr == "CREDIT").Sum(x => x.Amount);

                        string debit = amountDeb >= 0 ? "Rp. " + amountDeb.ToString("#,##") + ",00" : "Rp. " + amountDeb.ToString("#,##").Replace('-', '(') + ",00)";
                        string kredit = amountKre >= 0 ? "Rp. " + amountKre.ToString("#,##") + ",00" : "Rp. " + amountKre.ToString("#,##").Replace('-', '(') + ",00)";

                        <tr>
                            <td></td>
                            <td>@keyAccount</td>
                            <td>@debit</td>
                            <td>@kredit</td>
                            <td></td>
                        </tr>
                    }
                }
            }
        </tbody>
    </table>

</div>

<script>
    function openReport(evt, cityName) {
        // Declare all variables
        var i, tabcontent, tablinks;

        // Get all elements with class="tabcontent" and hide them
        tabcontent = document.getElementsByClassName("tabcontent");
        for (i = 0; i < tabcontent.length; i++) {
            tabcontent[i].style.display = "none";
        }

        // Get all elements with class="tablinks" and remove the class "active"
        tablinks = document.getElementsByClassName("tablinks");
        for (i = 0; i < tablinks.length; i++) {
            tablinks[i].className = tablinks[i].className.replace(" active", "");
        }

        // Show the current tab, and add an "active" class to the link that opened the tab
        document.getElementById(cityName).style.display = "block";
        evt.currentTarget.className += " active";
    }

    openReport(event, 'Grand');
</script>

ByDSync/Views/ReportGrand/Index.cshtml
@using ByDSync.Schema
@model IEnumerable<ByDSync.Schema.ReportGL>

@{
    ViewBag.Title = "Index";
}

<style>
    th, td {
        border: 7px solid transparent;
    }

    * {
        box-sizing: border-box
    }

    .container {
        width: 100%;
    }

    /* Style the tab */
    .tab {
        float: left;
        border: 1px solid #ccc;
        background-color: #f1f1f1;
        width: 10%;
        height: 300px;
    }

        /* Style the buttons that are used to open the tab content */
        .tab button {
            display: block;
            background-color: inherit;
            color: black;
            padding: 22px 16px;
            width: 100%;
            border: none;
            outline: none;
            text-align: left;
            cursor: pointer;
            transition: 0.3s;
        }

            /* Change background color of buttons on hover */
            .tab button:hover {
                background-color: #ddd;
            }

            /* Create an active/current "tab button" class */
            .tab button.active {
                background-color: #ccc;
            }

    /* Style the tab content */
    .tabcontent {
        float: left;
        padding: 0px 12px;
        border: 1px solid #ccc;
        width: 90%;
        border-left: none;
    }

    #filter {
        padding: 15px;
        margin-inline: 150px;
    }

    #filter button{
        margin-inline-start: 10px;
    }
</style>

<div class="tab">
    <button class="tablinks" onclick="openReport(event, 'Grand')">Report Grand</button>
    <button class="tablinks" onclick="openReport(event, 'Total')">Report Total</button>
    <button class="tablinks" onclick="openReport(event, 'Coa')">Report Detail COA</button>
</div>

@{ 
    var stepClosing = ViewData["ClosingStep"] as IEnumerable<enum_container>;
}

<div id="filter">
    @using (Html.BeginForm("Filter", "ReportGrand", FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        @Html.Label("From")
        <input type="date" name="begin" placeholder="dd-mm-yyyy" value="" min="1997-01-01" max="2050-12-31">
        @Html.Label("To")
        <input type="date" name="end" placeholder="dd-mm-yyyy" value="" min="1997-01-01" max="2050-12-31">
        @Html.Label("Closing Step")
        <select name="closingStep" id="cars">
            @foreach (var val in stepClosing)
            {
                <option value="@val.enumNumber">@val.enumDescription</option>
            }
        </select>
        <button type="submit" onclick="location.href = '@Url.Action("Filter", "ReportGrand")'">Filter Report</button>
    }
</div>

<div id="Grand" class="tabcontent">
    <h2>Report Grand</h2>
    @{
        var groupGrand = Model.GroupBy(x => x.Funding_Source_1, (key, g) => new { FundingSource = key, SumGrand = g.Sum(x => x.Amount) });
        //var detailGrand = Model.ToList();
    }

    <table>
        <thead>
            <tr>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
            </tr>
        </thead>

        <tbody>

            @foreach (var itemGrand in groupGrand)
            {
                string fundingGrand = itemGrand.FundingSource != null ? itemGrand.FundingSource : "N/A";

                <tr>
                    <td colspan="4"><h4>Grand :  @fundingGrand</h4></td>
                </tr>

                var detailGrand = (from r in Model
                                   where r.Funding_Source_1 == itemGrand.FundingSource
                                   group r by r.GL_Account into newDetail
                                   orderby newDetail.Key
                                   select newDetail);

                string sumGrand = itemGrand.SumGrand >= 0 ? "Rp. " + ((decimal)itemGrand.SumGrand).ToString("##,#") + ",00" : "Rp. " + ((decimal)itemGrand.SumGrand).ToString("##,#").Replace('-', '(') + ",00)";

                foreach (var detail in detailGrand)
                {
                    var sumAmount = detail.Sum(x => x.Amount);

                    string amountString = sumAmount >= 0 ? "Rp. " + ((decimal)sumAmount).ToString("##,#") + ",00" : "Rp. " + ((decimal)sumAmount).ToString("##,#").Replace('-', '(') + ",00)";

                    <tr>
                        <td></td>
                        <td><b>@detail.Key</b></td>
                        <td>@detail.First().GL_Account_Name.ToUpper()</td>
                        <td>@amountString</td>
                    </tr>
                }

                <tr>
                    <td colspan="4" align="right">@sumGrand</td>
                </tr>

            }
        </tbody>

    </table>
</div>

<div id="Total" class="tabcontent">
    <h2>Total</h2>

    @{
        var groupAccount = (from r in Model group r by r.GL_Account into account select account);

        decimal sumAll = (decimal)Model.Sum(x => x.Amount);
        string sumAllString = sumAll >= 0 ? "Rp. " + sumAll.ToString("#,##") + ",00" : "Rp. " + sumAll.ToString("#,##").Replace('-', '(') + ",00)";

        <table>

            @foreach (var akun in groupAccount)
            {
                decimal summa = (decimal)akun.Sum(x => x.Amount);
                var sumAccount = summa >= 0 ? "Rp. " + summa.ToString("#,##") + ",00" : "Rp. " + summa.ToString("#,##").Replace('-', '(') + ",00)";

                <tr>
                    <td><b>@akun.Key</b></td>
                    <td>@akun.First().GL_Account_Name.ToUpper() </td>
                    <td>@sumAccount</td>
                </tr>

            }

            <tr>
                <td colspan="3" align="right">
                    @sumAllString
                </td>
            </tr>

        </table>
    }
</div>

<div id="Coa" class="tabcontent">
    <h3>Detail COA</h3>

    <table>
        <thead>
            <tr>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @{
                var groupAcct = (from r in Model group r by r.GL_Account into newAccount select newAccount);

                foreach (var act in groupAcct)
                {
                    var groupFund = (from r in Model where r.GL_Account == act.Key group r by r.Funding_Source_1 into newFund select newFund);

                    <tr>
                        <td><h4>@act.Key</h4></td>
                        <td colspan="3"><h4>@act.First().GL_Account_Name.ToUpper()</h4></td>
                    </tr>

                    foreach (var fund in groupFund)
                    {
                        string keyAccount = fund.Key != null ? fund.Key : "N/A";

                        decimal amountDeb = (decimal)fund.Where(x => x.Dr_Cr == "DEBIT").Sum(x => x.Amount);
                        decimal amountKre = (decimal)fund.Where(x => x.Dr_Cr == "CREDIT").Sum(x => x.Amount);

                        string debit = amountDeb >= 0 ? "Rp. " + amountDeb.ToString("#,##") + ",00" : "Rp. " + amountDeb.ToString("#,##").Replace('-', '(') + ",00)";
                        string kredit = amountKre >= 0 ? "Rp. " + amountKre.ToString("#,##") + ",00" : "Rp. " + amountKre.ToString("#,##").Replace('-', '(') + ",00)";

                        <tr>
                            <td></td>
                            <td>@keyAccount</td>
                            <td>@debit</td>
                            <td>@kredit</td>
                            <td></td>
                        </tr>
                    }
                }
            }
        </tbody>
    </table>

</div>

<script>
    function openReport(evt, cityName) {
        // Declare all variables
        var i, tabcontent, tablinks;

        // Get all elements with class="tabcontent" and hide them
        tabcontent = document.getElementsByClassName("tabcontent");
        for (i = 0; i < tabcontent.length; i++) {
            tabcontent[i].style.display = "none";
        }

        // Get all elements with class="tablinks" and remove the class "active"
        tablinks = document.getElementsByClassName("tablinks");
        for (i = 0; i < tablinks.length; i++) {
            tablinks[i].className = tablinks[i].className.replace(" active", "");
        }

        // Show the current tab, and add an "active" class to the link that opened the tab
        document.getElementById(cityName).style.display = "block";
        evt.currentTarget.className += " active";
    }

    openReport(event, 'Grand');
</script>