TaxIdnProject/Pages/EFaktur/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using TaxIdnProject.Data;
using TaxIdnProject.Models;

namespace TaxIdnProject.Pages.EFaktur
{
    public class CreateModel : PageModel
    {
        private readonly TaxIdnProject.Data.TaxIdnContext _context;

        public CreateModel(TaxIdnProject.Data.TaxIdnContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public EFakturContainer EFakturContainer { get; set; } = default!;
        

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
          if (!ModelState.IsValid || _context.EFakturContainer == null || EFakturContainer == null)
            {
                return Page();
            }

            _context.EFakturContainer.Add(EFakturContainer);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

TaxIdnProject/Pages/EFaktur/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using TaxIdnProject.Data;
using TaxIdnProject.Models;

namespace TaxIdnProject.Pages.EFaktur
{
    public class DeleteModel : PageModel
    {
        private readonly TaxIdnProject.Data.TaxIdnContext _context;

        public DeleteModel(TaxIdnProject.Data.TaxIdnContext context)
        {
            _context = context;
        }

        [BindProperty]
      public EFakturContainer EFakturContainer { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.EFakturContainer == null)
            {
                return NotFound();
            }

            var efakturcontainer = await _context.EFakturContainer.FirstOrDefaultAsync(m => m.ID == id);

            if (efakturcontainer == null)
            {
                return NotFound();
            }
            else 
            {
                EFakturContainer = efakturcontainer;
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null || _context.EFakturContainer == null)
            {
                return NotFound();
            }
            var efakturcontainer = await _context.EFakturContainer.FindAsync(id);

            if (efakturcontainer != null)
            {
                EFakturContainer = efakturcontainer;
                _context.EFakturContainer.Remove(EFakturContainer);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

TaxIdnProject/Pages/EFaktur/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using TaxIdnProject.Data;
using TaxIdnProject.Models;

namespace TaxIdnProject.Pages.EFaktur
{
    public class DetailsModel : PageModel
    {
        private readonly TaxIdnProject.Data.TaxIdnContext _context;

        public DetailsModel(TaxIdnProject.Data.TaxIdnContext context)
        {
            _context = context;
        }

      public EFakturContainer EFakturContainer { get; set; } = default!; 

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.EFakturContainer == null)
            {
                return NotFound();
            }

            var efakturcontainer = await _context.EFakturContainer.FirstOrDefaultAsync(m => m.ID == id);
            if (efakturcontainer == null)
            {
                return NotFound();
            }
            else 
            {
                EFakturContainer = efakturcontainer;
            }
            return Page();
        }
    }
}

TaxIdnProject/Pages/EFaktur/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TaxIdnProject.Data;
using TaxIdnProject.Models;

namespace TaxIdnProject.Pages.EFaktur
{
    public class EditModel : PageModel
    {
        private readonly TaxIdnProject.Data.TaxIdnContext _context;

        public EditModel(TaxIdnProject.Data.TaxIdnContext context)
        {
            _context = context;
        }

        [BindProperty]
        public EFakturContainer EFakturContainer { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.EFakturContainer == null)
            {
                return NotFound();
            }

            var efakturcontainer =  await _context.EFakturContainer.FirstOrDefaultAsync(m => m.ID == id);
            if (efakturcontainer == null)
            {
                return NotFound();
            }
            EFakturContainer = efakturcontainer;
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(EFakturContainer).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!EFakturContainerExists(EFakturContainer.ID))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool EFakturContainerExists(int id)
        {
          return (_context.EFakturContainer?.Any(e => e.ID == id)).GetValueOrDefault();
        }
    }
}

TaxIdnProject/Pages/EFaktur/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using TaxIdnProject.Data;
using TaxIdnProject.Models;

namespace TaxIdnProject.Pages.EFaktur
{
    public class IndexModel : PageModel
    {
        private readonly TaxIdnContext _context;

        public IndexModel(TaxIdnContext context, ILogger<IndexModel> logger)
        {
            _context = context;
        }

        public IList<EFakturContainer> EFakturContainer { get;set; } = default!;

        public async Task OnGetAsync()
        {
            if (_context.EFakturContainer != null)
            {
                EFakturContainer = await _context.EFakturContainer.Where(a => a.isMasukan == true).ToListAsync();
            }
        }

        public ActionResult OnGetData()
        {
            ByDSync byDSync = new ByDSync(_context);

            //byDSync.populateEfakturIn();

            return LocalRedirect("/Efaktur");
        }

        public ActionResult OnPostData()
        {
            ByDSync byDSync = new ByDSync(_context);

            DateOnly tanggalDari = Request.Form["dariTanggal"] != "" ? DateOnly.Parse(Request.Form["dariTanggal"]) : DateOnly.MinValue;
            DateOnly tanggalSampai = Request.Form["sampaiTanggal"] != "" ? DateOnly.Parse(Request.Form["sampaiTanggal"]) : DateOnly.MaxValue;
            string kodeSupplier = Request.Form["kodeSupplier"];


            if(tanggalDari == DateOnly.MinValue)
            {
                ViewData["WarningMessage"] = "Tanggal Dari Harap Diisi untuk menghindari overload data!";
                return null;
            }

            if (tanggalSampai == DateOnly.MaxValue)
            {
                ViewData["WarningMessage"] = "Tanggal Sampai Harap Diisi untuk menghindari overload data!";
                return null;
            }

            byDSync.populateEfakturIn(tanggalDari, tanggalSampai, kodeSupplier);

            return LocalRedirect("/Efaktur");
        }
        public IActionResult OnGetCSV()
        {
            ByDSync byDSync = new ByDSync(_context);

            MemoryStream stream = new MemoryStream();
            
            byDSync.generateCSV(stream, false);
            stream.Position = 0;

            return File(stream, "application/octet-stream", "EFakturIn.csv");
        }
    }
}

TaxIdnProject/Pages/EFakturOut/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using TaxIdnProject.Data;
using TaxIdnProject.Models;

namespace TaxIdnProject.Pages.EFakturOut
{
    public class CreateModel : PageModel
    {
        private readonly TaxIdnProject.Data.TaxIdnContext _context;

        public CreateModel(TaxIdnProject.Data.TaxIdnContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public EFakturContainer EFakturContainer { get; set; } = default!;
        

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
          if (!ModelState.IsValid || _context.EFakturContainer == null || EFakturContainer == null)
            {
                return Page();
            }

            _context.EFakturContainer.Add(EFakturContainer);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

TaxIdnProject/Pages/EFakturOut/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using TaxIdnProject.Data;
using TaxIdnProject.Models;

namespace TaxIdnProject.Pages.EFakturOut
{
    public class DeleteModel : PageModel
    {
        private readonly TaxIdnProject.Data.TaxIdnContext _context;

        public DeleteModel(TaxIdnProject.Data.TaxIdnContext context)
        {
            _context = context;
        }

        [BindProperty]
      public EFakturContainer EFakturContainer { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.EFakturContainer == null)
            {
                return NotFound();
            }

            var efakturcontainer = await _context.EFakturContainer.FirstOrDefaultAsync(m => m.ID == id);

            if (efakturcontainer == null)
            {
                return NotFound();
            }
            else 
            {
                EFakturContainer = efakturcontainer;
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null || _context.EFakturContainer == null)
            {
                return NotFound();
            }
            var efakturcontainer = await _context.EFakturContainer.FindAsync(id);

            if (efakturcontainer != null)
            {
                EFakturContainer = efakturcontainer;
                _context.EFakturContainer.Remove(EFakturContainer);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

TaxIdnProject/Pages/EFakturOut/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using TaxIdnProject.Data;
using TaxIdnProject.Models;

namespace TaxIdnProject.Pages.EFakturOut
{
    public class DetailsModel : PageModel
    {
        private readonly TaxIdnProject.Data.TaxIdnContext _context;

        public DetailsModel(TaxIdnProject.Data.TaxIdnContext context)
        {
            _context = context;
        }

      public EFakturContainer EFakturContainer { get; set; } = default!; 

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.EFakturContainer == null)
            {
                return NotFound();
            }

            var efakturcontainer = await _context.EFakturContainer.FirstOrDefaultAsync(m => m.ID == id);
            if (efakturcontainer == null)
            {
                return NotFound();
            }
            else 
            {
                EFakturContainer = efakturcontainer;
            }
            return Page();
        }
    }
}

TaxIdnProject/Pages/EFakturOut/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TaxIdnProject.Data;
using TaxIdnProject.Models;

namespace TaxIdnProject.Pages.EFakturOut
{
    public class EditModel : PageModel
    {
        private readonly TaxIdnProject.Data.TaxIdnContext _context;

        public EditModel(TaxIdnProject.Data.TaxIdnContext context)
        {
            _context = context;
        }

        [BindProperty]
        public EFakturContainer EFakturContainer { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.EFakturContainer == null)
            {
                return NotFound();
            }

            var efakturcontainer =  await _context.EFakturContainer.FirstOrDefaultAsync(m => m.ID == id);
            if (efakturcontainer == null)
            {
                return NotFound();
            }
            EFakturContainer = efakturcontainer;
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(EFakturContainer).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!EFakturContainerExists(EFakturContainer.ID))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool EFakturContainerExists(int id)
        {
          return (_context.EFakturContainer?.Any(e => e.ID == id)).GetValueOrDefault();
        }
    }
}

TaxIdnProject/Pages/EFaktur/Index.cshtml
@page
@model TaxIdnProject.Pages.EFaktur.IndexModel

@{
    ViewData["Title"] = "Efaktur Masukan";
}

<h1>EFaktur Masukan Staging</h1>

@if (ViewData["WarningMessage"] != null)
{
    <script type="text/javascript">
        window.onload = function () {
            alert("@ViewData["WarningMessage"]");
        }
    </script>
}

<form asp-page-handler="Data" method="post">
    <div id="exampleModal" class="modal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Filter Supplier Invoice</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <table>
                        <tr>
                            <div class="form-group">
                                <td><label>Dari Tanggal</label></td>
                                <td>:</td>
                                <td><input id="dariTanggal" name="dariTanggal" type="date" /></td>
                            </div>
                        </tr>
                        <tr>
                            <div class="form-group">
                                <td><label>Sampai Tanggal</label></td>
                    <td>:</td>
                                <td><input id="sampaiTanggal" name="sampaiTanggal" type="date" /></td>
                            </div>
                        </tr>
                        <tr>
                            <div class="form-group">
                                <td><label>Kode Supplier</label></td>
                                <td>:</td>
                                <td><input id="kodeSupplier" name="kodeSupplier" type="text" value="" /></td>
                            </div>
                        </tr>
                    </table>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary">Get List</button>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
</form>

@if (Model != null)
{
    <script type="text/javascript">
        
    </script>
}

<p>
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">Get List</button>
    <a class="btn btn-primary" asp-page-handler="CSV">Generate CSV</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.EFakturContainer[0].KD_JENIS_TRANSAKSI)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EFakturContainer[0].FG_PENGGANTI)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EFakturContainer[0].NOMOR_FAKTUR)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EFakturContainer[0].MASA_PAJAK)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EFakturContainer[0].TANGGAL_FAKTUR)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EFakturContainer[0].NPWP)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EFakturContainer[0].NAMA)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EFakturContainer[0].ALAMAT_LENGKAP)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EFakturContainer[0].JUMLAH_DPP)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EFakturContainer[0].JUMLAH_PPN)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EFakturContainer[0].JUMLAH_PPNBM)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EFakturContainer[0].ID_KETERANGAN_TAMBAHAN)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EFakturContainer[0].FG_UANG_MUKA)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EFakturContainer[0].UANG_MUKA_DPP)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EFakturContainer[0].UANG_MUKA_PPN)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EFakturContainer[0].UANG_MUKA_PPNBM)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EFakturContainer[0].REFERENSI)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EFakturContainer[0].KODE_DOKUMEN_PENDUKUNG)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EFakturContainer[0].KODE_OBJEK)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EFakturContainer[0].NAMA_OBJEK)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EFakturContainer[0].HARGA_SATUAN)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EFakturContainer[0].JUMLAH_BARANG)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EFakturContainer[0].HARGA_TOTAL)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EFakturContainer[0].DISKON)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EFakturContainer[0].DPP)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EFakturContainer[0].PPN)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EFakturContainer[0].TARIF_PPNBM)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EFakturContainer[0].PPNBM)
            </th>
        </tr>
    </thead>
    <tbody>
        @if (Model.EFakturContainer != null)
        {
            @foreach (var item in Model.EFakturContainer)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.KD_JENIS_TRANSAKSI)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.FG_PENGGANTI)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.NOMOR_FAKTUR)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.MASA_PAJAK)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TANGGAL_FAKTUR)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.NPWP)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.NAMA)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ALAMAT_LENGKAP)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.JUMLAH_DPP)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.JUMLAH_PPN)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.JUMLAH_PPNBM)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ID_KETERANGAN_TAMBAHAN)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.FG_UANG_MUKA)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.UANG_MUKA_DPP)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.UANG_MUKA_PPN)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.UANG_MUKA_PPNBM)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.REFERENSI)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.KODE_DOKUMEN_PENDUKUNG)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.KODE_OBJEK)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.NAMA_OBJEK)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.HARGA_SATUAN)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.JUMLAH_BARANG)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.HARGA_TOTAL)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DISKON)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DPP)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PPN)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TARIF_PPNBM)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PPNBM)
                    </td>
                </tr>
            }
        }
    </tbody>
</table>